voice_ids = ["Aditi", "Amy", "Astrid", "Bianca", "Brian", "Camila", "Carla",
             "Carmen", "Celine", "Chantal", "Conchita", "Cristiano", "Dora",
             "Emma", "Enrique", "Ewa", "Filiz", "Gabrielle", "Geraint",
             "Giorgio", "Gwyneth", "Hans", "Ines", "Ivy", "Jacek", "Jan",
             "Joanna", "Joey", "Justin", "Karl", "Kendra", "Kevin", "Kimberly",
             "Lea", "Liv", "Lotte", "Lucia", "Lupe", "Mads", "Maja", "Marlene",
             "Mathieu", "Matthew", "Maxim", "Mia", "Miguel", "Mizuki", "Naja",
             "Nicole", "Olivia", "Penelope", "Raveena", "Ricardo", "Ruben",
             "Russell", "Salli", "Seoyeon", "Takumi", "Tatyana", "Vicki",
             "Vitoria", "Zeina", "Zhiyu"]

eng_language_code_dict = {"en-AU": "Australian English",
                          "en-IN": "Indian English",
                          "en-IE": "Irish English",
                          "en-NZ": "New Zealander Kiwi English",
                          "en-ZA": "South African English",
                          "en-GB": "English English",
                          "en-US": "American English",
                          "en-GB-WLS": "Welsh English"}

eng_language_name_dict = {"Australian English": "en-AU",
                          "Indian English": "en-IN",
                          "Irish English": "en-IE",
                          "New Zealander Kiwi English": "en-NZ",
                          "South African English": "en-ZA",
                          "English English": "en-GB",
                          "American English": "en-US",
                          "Welsh English": "en-GB-WLS"}

output_formats = ["json", "mp3", "ogg_vorbis", "pcm"]

sample_rates = ["8000", "16000", "22050", "24000"]

sample_sentences = ["The birch canoe slid on the smooth planks.",
                    "Glue the sheet to the dark blue background.",
                    "These days a chicken leg is a rare dish.",
                    "Rice is often served in round bowls.",
                    "The juice of lemons makes fine punch.",
                    "The box was thrown beside the parked truck.",
                    "The hogs were fed chopped corn and garbage.",
                    "Four hours of steady work faced us.",
                    "A large size in stockings is hard to sell.",
                    "The boy was there when the sun rose.",
                    "A rod is used to catch pink salmon.",
                    "The source of the huge river is the clear spring.",
                    "Kick the ball straight and follow through.",
                    "Help the woman get back to her feet.",
                    "A pot of tea helps to pass the evening.",
                    "Smoky fires lack flame and heat.",
                    "The salt breeze came across from the sea.",
                    "The girl at the booth sold fifty bonds.",
                    "The small pup gnawed a hole in the sock.",
                    "The fish twisted and turned on the bent hook.",
                    "Press the pants and sew a button on the vest.",
                    "The swan dive was far short of perfect.",
                    "The beauty of the view stunned the young boy.",
                    "Two blue fish swam in the tank.",
                    "Her purse was full of useless trash.",
                    "The colt reared and threw the tall rider.",
                    "It snowed, rained, and hailed the same morning.",
                    "Read verse out loud for pleasure.",
                    "Our Favorite Quotes by Shakespeare",
                    "One touch of nature makes the whole world kin.",
                    "We know what we are but know not what we may be.",
                    "No legacy is so rich as honesty.",
                    "Give every man thy ear, but few thy voice.",
                    "Uneasy lies the head that wears a crown.",
                    "Nothing will come of nothing.",
                    "Though she be but little, she is fierce.",
                    "I wasted time, and now doth time waste me.",
                    "Small cheer and great welcome makes a merry feast.",
                    "In time we hate that which we often fear.",
                    "Ambition should be made of sterner stuff.",
                    "Neither a borrower nor a lender be.",
                    "With mirth and laughter let old wrinkles come.",
                    "I bear a charmed life.",
                    "Modest doubt is called the beacon of the wise.",
                    "Boldness be my friend.",
                    "Words without thoughts never to heaven go.",
                    "Wisely and slow. They stumble that run fast.",
                    "Pleasure and action make the hours seem short.",
                    "All that glisters is not gold.",
                    "Such as we are made of, such we be.",
                    "The fault. is not in our stars but in ourselves.",
                    "Brevity is the soul of wit.",
                    "Give sorrow words. The grief that does not speak",
                    "Et tu, Brute?",
                    "That one may smile and smile and be a villain.",
                    "Let me be that I am and seek not to alter me.",
                    "Suspicion always haunts the guilty mind.",
                    "Conscience does make cowards of us all.",
                    "Be great in act, as you have been in thought.",
                    "April. hath put a spirit of youth in everything.",
                    "All things are ready if our minds be so.",
                    "The tempter or the tempted, who sins most?",
                    "Thought is free.",
                    "He jests at scars that never felt a wound.",
                    "Men should be what they seem.",
                    "Love is too young to know what conscience is.",
                    "If music be the food of love, play on.",
                    "Love all, trust a few, do wrong to none.",
                    "Love is a smoke made with the fume of sighs.",
                    "The course of true love never did run smooth.",
                    "In black ink my love may still shine bright.",
                    "Speak low, if you speak love.",
                    "Love sought is good, but given unsought is better.",
                    "Love comforteth like sunshine after rain.",
                    "For you, in my respect, are all the world.",
                    "Love is merely a madness.",
                    "I would my horse had the speed of your tongue.",
                    "Misery acquaints a man with strange bedfellows.",
                    "Lord, what fools these mortals be!",
                    "I will praise any man that will praise me.",
                    "Better a witty fool than a foolish wit.",
                    "My pride fell with my fortunes.",
                    "There’s many a man hath more hair than wit.",
                    "I dote on his very absence.",
                    "I am not bound to please thee with my answers.",
                    "A lover’s eyes will gaze an eagle blind.",
                    "Be wary, then; best safety lies in fear.",
                    "The private wound is deepest.",
                    "Of all base passions, fear is most accursed.",
                    "There’s beggary in the love that can be reckoned.",
                    "A heaven on earth I have won by wooing thee.",
                    "Thee will I love, and with thee lead my life.",
                    "To mingle friendship far is mingling bloods.",
                    "Serenity now, insanity later.",
                    "Just remember, it's not a lie if you believe it."]
